### ISSUE TITLE
issue when running osv-scanner on project running with golang 1.22 

### ISSUE THREAD

**Issue by felangga** [google/osv-scanner#1123]
Hello, I have some issues with my project which uses golang v1.22.5. 
On the CI, I'm pulling the latest version of OSV-scanner from ghcr.io. 

```
osv-scanner:
    runs-on: xxx
    container: ghcr.io/google/osv-scanner:v1.8.2
        ....
```

I got this error when running the osv-scanner, does it because the osv-scanner was built using go v1.21?
```
This application uses version go1.21 of the source-processing packages but runs version go1.22 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
```
