### ISSUE TITLE
Support ignoring a package only from license scanning

### ISSUE THREAD

**Issue by shahar-h** [google/osv-scanner#1124]
Today `[[PackageOverrides]]` can be configured to ignore a package entirely from both vulnerability and license scanning using `ignore` field:
```toml
[[PackageOverrides]]
# The package name, version, and ecosystem to match against
name = "lib"
# If version is not set or empty, it will match every version
version = "1.0.0"
ecosystem = "Go"
# Ignore this package entirely, including license scanning
ignore = true
```

However, there are cases where we only want to ignore a package from license scanning, for example when the package is only used in tests we may still want to detect vulnerabilities but ignore license since this package is not compiled in our application.
