### ISSUE TITLE
license checker not ignoring dev

### ISSUE THREAD

**Issue by jayvdb** [google/osv-scanner#1298]
I have the following config

```toml
[[PackageOverrides]]
group = "dev"
license.ignore = true
```

When I run `osv-scanner --experimental-licenses-summary pnpm-lock.yaml` , the summary contains the same list as when I run it without that config.

And when running with `--experimental-licenses MIT,ISC,Apache-2.0,..` I see failures in dev dependencies.

**Comment by jayvdb** [comment]
I noticed when putting in a set of `[[PackageOverrides]]` explicitly mentioning npm packages, that I needed to remove `group = "dev"` for the license checker to whitelist them.
So maybe this a generic npm "dev" problem, or user error/understanding.

**Comment by G-Rath** [comment]
I assume you're using the latest pnpm whose lockfile version no longer marks dev dependencies as such, so currently the scanner has to assume all dependencies are  in no groups.

The main path to improving this is supporting extracting information from supporting files (which in this case would be package.json), whichll hopefully be worked on soon after the upcoming V2.

There's an issue open for that if you search (I'm on mobile and can't remember the number off hand 😅)

**Comment by jayvdb** [comment]
We are using lock 9.0 , which you added support for in https://github.com/google/osv-scanner/pull/934

It does separate prod vs dev
```yaml

importers:

  .:
    dependencies:
      '@...':
    devDependencies:
      '@...':
```

I looked again and didnt find any issues or PRs about it.
