### ISSUE TITLE
Grace Period Based on Severity

### ISSUE THREAD

**Issue by hi-artem** [google/osv-scanner#1442]
It would be nice to allow extend configuration to allow grace period based on severity.

For example something like this:

```toml
[[IgnoredVulns]]
severity = "LOW"
gracePeriod = 180


[[IgnoredVulns]]
severity = "MEDIUM"
gracePeriod = 90


[[IgnoredVulns]]
severity = "HIGH"
gracePeriod = 30
```
