### ISSUE TITLE
Support docker-based pre-commit

### ISSUE THREAD

**Issue by yu-iskw** [google/osv-scanner#1448]
## Motivation

osv-scanner supports the pre-commit hook `osv-scanner`. It would be useful to offer another hook to run osv-scanner in docker.

https://github.com/google/osv-scanner/blob/f75ac88212a027207f56199bc32da8fca2e95d47/.pre-commit-hooks.yaml

For instance, [rhysd/actionlint] (https://github.com/rhysd/actionlint) provides the pre-commit hook `actionlint-docker`. That enables us to run the pre-commit hook in docker.

```
---
repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint-docker
```
