### ISSUE TITLE
Renovate-bot does not seem to be working

### ISSUE THREAD

**Issue by wolf99** [google/osv-scanner#145]
I noticed that some Actions in the CI Workflows in this repo appear to be out of date.
Checking old PRs it doesn't look like renovate-bot is doing much.

It would be easy to add dependabot instead.
At least for Github Actions it would only need

```yaml
version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

Do I misunderstand the use of Renovate-bot here?
Is there any reson not to add dependabot?

Happy to open a PR if it is wanted 🙂
