### ISSUE TITLE
[Feature] Provide CI ready docker container

### ISSUE THREAD

**Issue by cromefire** [google/osv-scanner#154]
Because some CI systems like GitLab CI use docker images as base it would be pretty great, if an image with a shell would be provided. An [example](https://github.com/GoogleContainerTools/kaniko#debug-image) can be found in the kaniko project, which provides a `:debug` tag for this purpose.

Why is a shell needed? Systems like GitLab CI mount the source code into the container and then open a shell inside of the container to execute user defined commands on the source code. And to open that shell inside of the container, `sh` (or even something compatible) must be available.

**Comment by oliverchang** [comment]
Thanks for filing this issue! This seems like a pretty easy use case to support. @another-rex thoughts?

**Comment by another-rex** [comment]
Our current container image (ghcr.io/google/osv-scanner:v1.1.0) is based off of an alpine base image, which does have `/bin/sh` available. (e.g. `docker run -it --entrypoint=/bin/sh ghcr.io/google/osv-scanner:v1.1.0` works).

Do gitlab need the shell as the default entrypoint?

**Comment by cromefire** [comment]
Hmm will have a look again, normally it just find the shell binary and runs it, but I think you can also override the entry point manually, so I'll give that a try.

**Comment by tommiv** [comment]
@another-rex as for me, I simply forgot there is ghcr.io. I've searched dockerhub, haven't found an official image and subscribed to this issue. It might be a good idea to reflect the official image address in an "Installation" section of readme.

@cromefire given that the official image exists, in Gitlab CI it's as easy as:
```yaml
scan_deps:
  stage: code_quality
  image:
    name: "ghcr.io/google/osv-scanner:v1.1.0" # or :latest if you prefer
    entrypoint: [""]
  script:
    - /osv-scanner ${CI_PROJECT_DIR}
  allow_failure: true
```
I've checked – it works for me.
