### ISSUE TITLE
"Conditional binary operator expected" error

### ISSUE THREAD

**Issue by BigBlueHat** [google/osv-scanner#1995]
Whenever I try to use this action, I get the following error...seemingly during a scan:
```
Scanning dir ./
Scanned /github/workspace/package-lock.json file and found 273 packages
/root/exit_code_redirect.sh: line 48: conditional binary operator expected
Exit code: 0
/root/exit_code_redirect.sh: line 48: syntax error near `="-allow-no-lockfiles"'
/root/exit_code_redirect.sh: line 48: `      [[ "$value" ="-allow-no-lockfiles" ]] ||'
```

As you can see the `package-lock.json` file is found, though, the same error is thrown even if that fails.

The issue persists even if I set scan-args to include `--allow-no-lockfiles`.

Here's the action I'm working with:
```yaml
# OSV-Scanner PR scanning reusable workflow, can be used as a PR action to detect new vulnerabilities being introduced.
name: "OSV-Scanner PR Scanning"

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  contents: read
  security-events: write

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  osv-scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.0.3"
    with:
      scan-args: |-
        -r ./ --allow-no-lockfiles
```
