### ISSUE TITLE
Improve `IgnoredVulns` ergonomics

### ISSUE THREAD

**Issue by ericcornelissen** [google/osv-scanner#281]
This report concerns the `IgnoredVulns` [configuration](https://google.github.io/osv-scanner/configuration/) option, in particular the way it handles vulnerabilities known by multiple identifiers. At least for Rust(/Cargo), `osv-scanner` reports both `RUSTSEC` and `GHSA` advisories but ignoring by either one of these for a given vulnerabilities does not ignore the other. 

## Example

I have a Rust project that `osv-scanner` currently finds two vulnerabilities for:

```sh
$ osv-scanner .
Scanning dir .
Scanning .../rust-project/ at commit 1234567890abcdef
Scanned .../rust-project/Cargo.lock file and found 159 packages
╭─────────────────────────────────────┬───────────┬────────────────┬─────────┬────────────╮
│ OSV URL (ID IN BOLD)                │ ECOSYSTEM │ PACKAGE        │ VERSION │ SOURCE     │
├─────────────────────────────────────┼───────────┼────────────────┼─────────┼────────────┤
│ https://osv.dev/GHSA-mc8h-8q98-g5hr │ crates.io │ remove_dir_all │ 0.5.3   │ Cargo.lock │
│ https://osv.dev/RUSTSEC-2023-0018   │           │                │         │            │
│ https://osv.dev/GHSA-wcg3-cvx6-7396 │ crates.io │ time           │ 0.1.45  │ Cargo.lock │
│ https://osv.dev/RUSTSEC-2020-0071   │           │                │         │            │
╰─────────────────────────────────────┴───────────┴────────────────┴─────────┴────────────╯
```

Where the `GHSA` and `RUSTSEC` URLs/IDs for the same package are in fact for the same vulnerability (the CLI output suggests this, and the [osv.dev website](https://osv.dev/list) refers to them as _Aliases_). However, if I want to ignore these by, say, the `RUSTSEC` identifiers using:

```toml
# osv-scanner.toml

[[IgnoredVulns]]
id = "RUSTSEC-2023-0018"
reason = "TODO"

[[IgnoredVulns]]
id = "RUSTSEC-2020-0071"
reason = "TODO"
```

then running `osv-scanner` still outputs the `GHSA` URLs/IDs (and exits with a non-zero exit code):

```sh
$ osv-scanner .
Scanning dir .
Scanning .../rust-project/ at commit 1234567890abcdef
Scanned .../rust-project/Cargo.lock file and found 159 packages
╭─────────────────────────────────────┬───────────┬────────────────┬─────────┬────────────╮
│ OSV URL (ID IN BOLD)                │ ECOSYSTEM │ PACKAGE        │ VERSION │ SOURCE     │
├─────────────────────────────────────┼───────────┼────────────────┼─────────┼────────────┤
│ https://osv.dev/GHSA-mc8h-8q98-g5hr │ crates.io │ remove_dir_all │ 0.5.3   │ Cargo.lock │
│ https://osv.dev/GHSA-wcg3-cvx6-7396 │ crates.io │ time           │ 0.1.45  │ Cargo.lock │
╰─────────────────────────────────────┴───────────┴────────────────┴─────────┴────────────╯
```

I expected it to recognize these are the same vulnerabilities and thus ignore them as well. If that's not possible, I would request a more convenient configuration approach than (something like):

```toml
# osv-scanner.toml

[[IgnoredVulns]]
id = "RUSTSEC-2023-0018"
reason = "TODO"
[[IgnoredVulns]]
id = "GHSA-mc8h-8q98-g5hr"
reason = "Same as RUSTSEC-2023-0018"

[[IgnoredVulns]]
id = "RUSTSEC-2020-0071"
reason = "TODO"
[[IgnoredVulns]]
id = "GHSA-wcg3-cvx6-7396"
reason = "Same as RUSTSEC-2020-0071"
```

### Reproducibility information

- `osv-scanner` version (installed using `go install github.com/google/osv-scanner/cmd/osv-scanner@v1` on March 9, 2023):

  ```sh
  $ osv-scanner --version
  osv-scanner version: dev
  commit: n/a
  built at: n/a
  ```

- Rust version:

  ```sh
  $ rustc --version
  rustc 1.68.0 (2c8cc3432 2023-03-06)
  ```

- Cargo version:

  ```sh
  $ cargo version
  cargo 1.68.0 (115f34552 2023-02-26)
  ```

- Relevant manifest and content:

  ```toml
  # Cargo.toml

  [dependencies]
  clap = { version = "4.1.1", features = ["derive"] }
  log = "0.4.17"
  parse-display = "0.8.0"
  trash = "3.0.1"
  wild = "2.1.0"

  [dev-dependencies]
  assert_cmd = { version = "2.0.8", features = ["color-auto"] }
  assert_fs = "1.0.10"
  predicates = "2.1.5"
  proptest = "1.0.0"
  proptest-attr-macro = "1.0.0"
  proptest-derive = "0.3.0"
  rstest = "0.16.0"
  rstest_reuse = "0.5.0"
  ```

**Comment by oliverchang** [comment]
Thanks for filing this issue and bringing up this gap in our ignore file! 

@another-rex @michaelkedar I think one potential way to address this is to just add a boolean to each IgnoredVulns entry

i.e.

```toml
[[IgnoredVulns]]
id = "RUSTSEC-2023-0018"
reason = "TODO"
include_aliases = true
```

A separate question here is if `include_aliases` should be true by default . I think it should be, as it seems more like the exception to want to set this to false. @another-rex @michaelkedar thoughts?
