### ISSUE TITLE
Document GitHub actions

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#516]

**Comment by hayleycd** [comment]
Process has begun in #541

**Comment by hayleycd** [comment]
#541 has been merged! The basic docs are ready to be merged into the docs branch whenever you would like them to go live. However, I am keeping this open because there are upcoming pieces of additional documentation. 

- [ ] Documenting how to use flags, once that is incorporated into the functionality

- [ ] Writing copy for getting the action up on marketplace

**Comment by another-rex** [comment]
Flags have been added to the reusable actions. Let's add some examples for how to scan custom targets, what the defaults are, where to find all the flags.
E.g.:
```
# Scan specific lockifle
jobs:
  scan-pr:
    uses: "./.github/workflows/osv-scanner-reusable-pr.yml"
    with: 
      scan-args: |-
        ./path/to/lockfile1
        ./path/to/lockfile2
```

```
# Default
jobs:
  scan-pr:
    uses: "./.github/workflows/osv-scanner-reusable-pr.yml"
    with: 
      scan-args: |-
        -r
        --skip-git
        ./
```
